[project]
name = "custom-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docker==7.0.0",
    "flask==3.0.0",
    "redis>=7.0.1",
    "requests==2.31.0",
]
